name: Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      working-directory: MSUMALog
      run: dotnet restore MSUMALog.sln

    - name: Build
      working-directory: MSUMALog
      run: dotnet build MSUMALog.sln --configuration Release --no-restore

    - name: Test
      working-directory: MSUMALog
      run: dotnet test MSUMALog.Server.Tests/MSUMALog.Server.Tests.csproj --no-build --verbosity normal